name: Documentation CI
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:

permissions: {}

jobs:
  docs-ci:
    uses: grafana/writers-toolkit/.github/workflows/docs-ci.yml@4dbecae7443c69b3e5fdfeeac7037a339cb82e4c # main
    permissions:
      checks: write
      contents: read
      pull-requests: write
    with:
      build: true
      build-website-directory: content/docs/alloy/latest
      vale: true
